const MAX_HASHTAG_QUANTITY = 5;
const MAX_COMMENT_LENGTH = 140;

const MAX_COMMENTS_NUMBER = 50;
const MAX_START_VISIBLE_COMMENTS_NUMBER = 5;
const UPLOAD_COMMENTS_NUMBER = 5;

const SCALE_NUMBER_MIN = 25;
const SCALE_NUMBER_MAX = 100;
const SCALE_NUMBER_STEP = 25;

export {MAX_HASHTAG_QUANTITY, MAX_COMMENT_LENGTH, MAX_COMMENTS_NUMBER, MAX_START_VISIBLE_COMMENTS_NUMBER, UPLOAD_COMMENTS_NUMBER, SCALE_NUMBER_MIN, SCALE_NUMBER_MAX, SCALE_NUMBER_STEP};
